# Tugas Praktikum 4

# Naive Bayes Classifier

Ambil satu dataset dari pilihan berikut di sklearn:

1. Boston house prices dataset
2. Iris plants dataset
3. Diabetes dataset
4. Wine recognition dataset
5. Breast cancer wisconsin (diagnostic) dataset

Dataset bisa diakses melalui tautan berikut.
 __[scikit-learn.org/stable/datasets.html](https://scikit-learn.org/stable/datasets.html)__
 


Panduan untuk mengakses dataset bisa dilihat kembali di Praktikum 2 - Dataset dan Pandas

Ulang langkah-langkah yang dilakukan di Praktikum 4 - Naive Bayes Classifier sesuai dengan fitur di dataset terkait (cari nilai rata-rata dan median untuk fitur interval/rasio, transform dengan one-hot encoding fitur-fitur ordinal). Lakukan preprocessing lain jika perlu.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",
                 names = ("sepal length", "sepal width", "petal length", "petal width", "class"))

In [3]:
df.head()

sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
df

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
df['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [6]:
df['sepal length'].mean()

5.843333333333334

In [7]:
df['sepal length'].median()

5.8

In [8]:
df

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [9]:
X = df.drop('class', axis=1)
y = df['class']

In [10]:
# memisahkan dataset ke dalam set training dan set testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 1)

In [11]:
# melatih model dengan set training
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [12]:
# membuat prediksi hasil set testing
predictions = gnb.predict(X_test)

In [13]:
# membandingkan hasil prediksi dan label sesungguhnya
from sklearn.metrics import classification_report,confusion_matrix

In [14]:
print(classification_report(y_test,predictions))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       0.95      0.90      0.93        21
 Iris-virginica       0.90      0.95      0.93        20

       accuracy                           0.95        60
      macro avg       0.95      0.95      0.95        60
   weighted avg       0.95      0.95      0.95        60



In [15]:
print(confusion_matrix(y_test,predictions))

[[19  0  0]
 [ 0 19  2]
 [ 0  1 19]]
